CREATE OR REPLACE TABLE RAW.CUSTOMERS
(
CUSTOMER_ID INT,
FIRST_NAME STRING,
LAST_NAME STRING,
EMAIL STRING,
PHONE STRING,
STATE STRING,
COUNTRY STRING,
CREATED_DATE DATE
);

CREATE OR REPLACE TABLE RAW.TRANSACTIONS
(
TRANSACTION_ID INT,
CUSTOMER_ID INT,
PRODUCT_NAME STRING,
QUANTITY INT,
AMOUNT NUMBER(10,2),
TRANSACTION_DATE DATE
);

CREATE OR REPLACE TABLE CURATED.DIM_CUSTOMER
(
CUSTOMER_KEY INT AUTOINCREMENT,
CUSTOMER_ID INT,
CUSTOMER_NAME STRING,
EMAIL STRING,
STATE STRING,
COUNTRY STRING
);

CREATE OR REPLACE TABLE CURATED.FACT_SALES
(
TRANSACTION_ID INT,
CUSTOMER_KEY INT,
PRODUCT_NAME STRING,
QUANTITY INT,
AMOUNT NUMBER(10,2),
TRANSACTION_DATE DATE
);
